[versions]

#HEC Dependencies
metrics = "2.0"
service-annotations = "2.0.1"
lookup = "2.0"

#Third Party Dependencies
jackson = "2.17.2"
swagger-annotations = "2.2.22"
validation-api = "3.1.0"
annotation-api = "3.0.0"
swagger-codegen = "3.0.59"
jwt = "4.4.0"
okhttp = "4.12.0"

#Test Dependencies
junit = "5.10.3"

[libraries]
#HEC Dependencies

metrics = { module = "mil.army.usace.hec:metrics-services", version.ref = "metrics" }
metrics-codahale = { module = "mil.army.usace.hec:metrics-codahale", version.ref = "metrics" }

lookup = { module = "mil.army.usace.hec:lookup", version.ref = "lookup" }
service-annotations = { module = "mil.army.usace.hec:service-annotations", version.ref = "service-annotations" }

#Third-Party
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger-annotations" }
validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "validation-api" }
annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "annotation-api" }
swagger-codegen = { module = "io.swagger.codegen.v3:swagger-codegen-cli", version.ref = "swagger-codegen" }
jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }

#Test Dependencies
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }


